### PR TITLE
rosinstall: depend on released rxcpp_vendor.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Related: https://github.com/rosin-project/rxros/pull/25.

**Comment by gavanderhoorn** [comment]
Sync is expected [today](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-09-11/10631).

**Review by henrik7264 — APPROVED** [review]
OK with me.

**Comment by gavanderhoorn** [comment]
Merging as everything has been synced.

**Pull request merged**
